name: intellifarm
description: Our FYP.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  flutter_image_compress: ^2.3.0
  pdf: ^3.11.1
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  shared_preferences: ^2.3.2
  cloud_firestore: ^5.4.4
  intl: ^0.19.0
  firebase_storage: ^12.3.4
  connectivity_plus: ^4.0.0 # Keep its version to 4.0.0 as it was giving errors on newer versions
  provider: ^6.1.2
  path_provider: ^2.1.4
  permission_handler: ^11.3.1
  open_filex: ^4.5.0

dev_dependencies:
  flutter_launcher_icons: ^0.14.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  image_path: "assets/logo.png" # Make sure this path is correct and matches your project structure.

flutter:
  uses-material-design: true

  # Uncomment and update if needed
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
