// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJhFiecIt74ygsVuca5vN4pCG5dzu84Ao',
    appId: '1:125509152672:web:0b5619577b33a1e1463ec5',
    messagingSenderId: '125509152672',
    projectId: 'if-main-ee1e2',
    authDomain: 'if-main-ee1e2.firebaseapp.com',
    storageBucket: 'if-main-ee1e2.appspot.com',
    measurementId: 'G-G2Q4W19M4H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8jX9h2sAJv2PMDdVlEc2ItfvInvplRKo',
    appId: '1:125509152672:android:85db3e7020c5a6a1463ec5',
    messagingSenderId: '125509152672',
    projectId: 'if-main-ee1e2',
    storageBucket: 'if-main-ee1e2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCR25Slfaw0ECrgXEag5PM-4hBfLUB38_c',
    appId: '1:125509152672:ios:22a29920ba5924fa463ec5',
    messagingSenderId: '125509152672',
    projectId: 'if-main-ee1e2',
    storageBucket: 'if-main-ee1e2.appspot.com',
    iosBundleId: 'com.example.intellifarm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCR25Slfaw0ECrgXEag5PM-4hBfLUB38_c',
    appId: '1:125509152672:ios:22a29920ba5924fa463ec5',
    messagingSenderId: '125509152672',
    projectId: 'if-main-ee1e2',
    storageBucket: 'if-main-ee1e2.appspot.com',
    iosBundleId: 'com.example.intellifarm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJhFiecIt74ygsVuca5vN4pCG5dzu84Ao',
    appId: '1:125509152672:web:c37a8a300130d051463ec5',
    messagingSenderId: '125509152672',
    projectId: 'if-main-ee1e2',
    authDomain: 'if-main-ee1e2.firebaseapp.com',
    storageBucket: 'if-main-ee1e2.appspot.com',
    measurementId: 'G-MZZFDSQ5SL',
  );
}
